---
enable_ssh_over_tor: true

# Set the default SSH listening address for the sshd config file.
# If enable_ssh_over_tor is false, open up SSH (additional iptables templates
# helps us for restriction) otherwise restrict to localhost (tor).
ssh_listening_address: "{{ '127.0.0.1' if enable_ssh_over_tor else '0.0.0.0' }}"

# This var is defined in the tor-hidden-services role, but won't be available
# in separate plays, so declaring it within the context of iptables role, so
# the hostname files can be fetched back to the Admin Workstation.
tor_hidden_services_parent_dir: /var/lib/tor/services
